function [subject_id]=SIN_getsubjects
%% DESCRIPTION:
%
% Query existing subjects
%
%   Query based on existing directories. If the directories don't exist,
%   then we have to assume that no subject data has been collected. 
%
%   Code modified from:
%       http://stackoverflow.com/questions/8748976/list-the-subfolders-in-a-folder-matlab-only-subfolders-not-files
%
% INPUT:
%
%   None
%
% OUTPUT:
%
%   subject_id: cell array of subject IDs

% Get Subject directory
%   Pass empty subjectID (second input) to placate SIN_TestSetup (for now).
%   
subDir = SIN_TestSetup('Defaults', ''); 
subDir = subDir.general.subjectDir;
            
% Get Subject List
subject_id = dir(subDir); 

% Subject list generated by looking for directories
subject_id = {subject_id((vertcat(subject_id.isdir))).name};

% Remove '.' and '..' directories
subject_id(ismember(subject_id,{'.','..'})) = [];